//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Id { get; set; }
        public string Fname { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int GenderId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Status Status { get; set; }
    }
}
